---
format: 
  docx:
    reference-doc: my_styles.docx
    number-sections: true
title: "Ecosystem recovery of Tampa bay following the 2021 release of phosphate mine wastewater from the Piney Point facility"
bibliography: refs.bib
csl: apa.csl
crossref: 
  fig-title: Fig.
author:
  - Marcus W Beck:
      email: mbeck@tbep.org
      orcid: 0000-0002-4996-0059
      institute: [TBEP]
      correspondence: true
  - Edward T Sherwood:
      email: esherwood@tbep.org
      orcid: 0000-0001-5330-302X
      institute: [TBEP]
      correspondence: false
  - Sarina J Ergas:
      email: sergas@usf.edu
      orcid: 0000-0001-6820-7196
      institute: [USF]
      correspondence: false
  - Jeffrey A Cunningham:
      email: cunning@usf.edu
      orcid: 0000-0001-9654-8262
      institute: [USF]
      correspondence: false
  - David A Tomasko:
      email: dave@sarasotabay.org
      institute: [SBEP]
      correspondence: false
      
institute:
  - TBEP: Tampa Bay Estuary Program, 263 13th Ave S., Suite 350, St. Petersburg, Florida 33701 USA
  - USF: University of South Florida, Department of Civil and Environmental Engineering, 4202 East Fowler Avenue, ENG 030, Tampa, Florida 33620 USA
  - SBEP: Sarasota Bay Estuary Program, Sarasota, Florida 34236 USA

filters: 
  - templates/scholarly-metadata.lua
  - templates/author-info-blocks.lua
  
execute: 
  echo: false
  warning: false
  ft.keepnext: false
  ft.align: left
---

```{r}
#| results: hide
library(knitr)
```

## Abstract (150-250 words) {.unnumbered}

Mining activities can support local and global economies, yet also impose significant consequences for the natural environment. Phosphate mining in central Florida has been ongoing for decades and many facilities present risks to freshwater and coastal aquatic environments in the state. In 2021, a breach in the liner of a wastewater holding pond at Piney Point, a legacy phosphate processing facility, resulted in the emergency discharge of \~815 million liters of highly acidic and nutrient-laden (nitrogen, phosphorus) process water into Tampa Bay. A multi-agency, event-response monitoring program resulted, which documented ecosystem impacts within several months. Short-term declines in water quality were observed, with a notable harmful algal bloom and substantial fish kills occurring three months after the initial wastewater release. Acute spills like the 2021 event threaten past successes, while efforts to mitigate and prevent these negative outcomes in the future are ongoing. This chapter will present the historical context and management of Piney Point as a precursor to the events of 2021, while providing quantitative examples of the bay's response for interpretation relative to the long-term recovery of the bay. The role of the Tampa Bay Estuary Program as a non-regulatory institution that works to build public and private partnerships for bay management will also be explored, with emphasis on its role coordinating monitoring efforts and disseminating open science communication products.

{{< pagebreak >}}

## Introduction (500-1500 words)

Provide background for the instructor that helps integrate the case study into disciplinary material and, if possible, relate the case study to ABET General Criteria (Student Outcomes 1-7), Program Criteria for Civil Engineering and Environmental Engineering, and general definitions and statements (e.g., ABET’s Statement on Implementing DEI Concepts into Program Criteria). The references in this section should focus on pedagogical aspects of the case study. As Section Editor, I can assist with the latter.

ABET General Criteria Student Outcomes:

1. an ability to identify, formulate, and solve complex engineering problems by applying principles of engineering, science, and mathematics.

1. an ability to apply engineering design to produce solutions that meet specified needs with consideration of public health, safety, and welfare, as well as global, cultural, social, environmental, and economic factors.

1. an ability to communicate effectively with a range of audiences.

1. an ability to recognize ethical and professional responsibilities in engineering situations and make informed judgments, which must consider the impact of engineering solutions in global, economic, environmental, and societal contexts.

1. an ability to function effectively on a team whose members together provide leadership, create a collaborative and inclusive environment, establish goals, plan tasks, and meet objectives.

1. an ability to develop and conduct appropriate experimentation, analyze and interpret data, and use engineering judgment to draw conclusions.

1. an ability to acquire and apply new knowledge as needed, using appropriate learning strategies.

Regarding DEI. The ABET information can be found here <https://www.abet.org/about-abet/idea-inclusion-diversity-equity-accessibility/> Social justice issues relevant to the spill could be addressed.

This case study provides an example of the roles and responsibilities of public institutions and private organizations and how they can work together to address environmental problems (Environmental Engineering Program Criterion e)

My notes:

This is about bay management as the engineering challenge - strength of partnerships, key players, and how they work together to manage the bay.  What are the threats and challenges to bay management? How has it been effective in the past? What is the role of TBEP and, more generally, research/volunteerism/regulation? This is the engineering problem.

Managing the bay and protecting water quality is the design process, constraints to this are economic, political, and social forces that are at odds with environmental protection

Role of data/monitoring to support bay management - make this a key concept that relates to Piney Point. 

Introduce mining as an economic driver in Central Florida, highlight past environmental issues with mining in the region (earlier Piney Point spills, Mosaic/Alafia), also chronic issues with port facilities and fertilizer losses

What is it about fertilizer mining that creates problems? A waste-intensive process... many facilities located near critical infrastructure to support transport (ports)

Introduce Piney Point and events of 2021

In February 1974, a news segment airing on Sixty Minutes drew national attention on the effects of population growth and unchecked development in the Tampa Bay region.  Noxious macroalgal blooms, loss of seagrass, and a decline in fisheries were evidence of the effects of this growth as the bay's natural resources were stressed by an increasing human population. The discharge of untreated wastewater into Tampa Bay was a culprit for many of these maladies. Over the following decades, efforts to restore Tampa Bay were successful in reducing external nutrient loads by 2/3 and seagrasses recovered to an all-time high (since recorded) of 41,656 acres in 2016, exceeding the management goal by several thousand acres. Effective management of the natural environment requires dedicated public and private efforts to balance competing interests for how human activities affect natural resources. The contemporary history of Tampa Bay, Florida is an exemplary model for how collaborative efforts can successfully recover a degraded aquatic environment.   

Efforts contributing to the recovery of Tampa Bay are the product of multiple factors, some of which were opportune while others were more intentional.  In the 1960s, a growing nationwide environmental movement influenced public sentiment on how unregulated economic growth and development can severely harm the environment.  Notable events such as the Cuyahoga River catching on fire and widely read texts like "Silent Spring" were influential factors that motivated change in a national environmental ethic. These sentiments trickled down to Tampa Bay communities as local environmental disasters combined with massive population growth lead to public calls for regulatory reform and environmental restoration. Focus was on the discharge of untreated sewage directly to the bay, as legislation was passed that required all wastewater treatment plants to upgrade to advanced treatment technologies, in addition to tighter controls on stormwater pollution.  These efforts were reinforced at the federal level with enactment of the Clean Water Act in the same year. Gradually and over several decades, water quality in the bay improved and the seagrasses returned, supported by hundreds of habitat and infrastructure restoration projects lead by numerous public entities.

Local public and private environmental groups continue to be key players in coalescing public support to improve water quality in Tampa Bay. The Tampa Bay Estuary Program (TBEP), in particular, has been a consistent voice over the last three decades that has worked to build partnerships to restore and protect the bay.  This work is implemented through a scientifically sound, community-based management plan.  The TBEP is part of a broader National Estuary Program consisting of 28 similar programs around the country that have been established at Congressionally recognized "estuaries of national significance", each with their own locally-specific mission.  Since 1991, the TBEP has worked to engage local communities, private businesses, and local governments to work towards the common good of a healthy Tampa Bay.  The TBEP also manages the Tampa Bay Nitrogen Management Consortium that has worked to reduce nitrogen loads as a key pollutant to the Bay, with a primary source being wastewater and stormwater.  The management approach is simple; reduced nitrogen loads will produce less algal growth, promoting a light environment in the water that is supportive of seagrass growth.  The TBNMC has quantified and allocated sources of nitrogen among public and private entities that directly or indirectly discharge to the bay, with totals not to exceed based on the capacity of the Bay to assimilate these nutrients.  The Florida Department of Environmental Protection (FDEP) maintains regulatory oversight.

Despite the nationally recognized story of Tampa Bay, current challenges have emerged that threaten past successes and bring into question the effectiveness of existing management paradigms.  From 2016 to 2022, seagrasses declined baywide by over 11,000 acres, falling well below the management target of 40,000 acres.  These declines were notable because water quality goals were met in successive years of seagrass decline, suggesting that additional factors were driving this loss. Recent interest has shifted towards climate change as a potential culprit as extreme temperatures and changes in precipitation may be stressing seagrasses beyond their optimal tolerance ranges.  These additional stressors mean that further reductions in nutrient loads may be needed to account for external climate factors that are difficult, if not impossible, to control at the local scale.  Resilience of the bay to assimilate nutrient inputs has likely been reduced as shifting baselines from climate change cause regional managers to reconsider the effectiveness of past targets and thresholds. 

Reduced resilience of Tampa Bay to respond to management efforts threatens to undo the years of collaborative work in restoring seagrasses.  Unanticipated events may push the bay beyond a tipping point to a condition similar to the past as the bay may no longer have the capacity to process excess nutrient inputs.  Events in 2021 were a substantial test for the management of Tampa Bay that provided an unintentional system-wide experiment for how the bay's resources respond to acute nutrient inputs.  The Piney Point facility is located on the southeast shoreline of Tampa Bay and is a legacy phosphorus fertilizer processing facility that has been inactive for over twenty years.  Large amounts of wastewater as a byproduct of historical processing are stored on site, with no useful application given the chemical characteristics of the water.  Central Florida has had a long and complicated history with fertilizer mining.  While these activities support economic growth, there are often unintended consequence for the natural environment.  Piney Point embodies this relationship, as fertilizer export from nearby Port Manatee has supported the local economy, whereas wastewater stored on site has made its way to Tampa Bay on more than one occasion.  

In April 2021, a tear in the plastic liner of the southeastern holding pond (NGS-S) at Piney Point was detected and the release of wastewater into Tampa Bay was authorized by FDEP to prevent catastrophic failure of the pond walls.  The decision to discharge millions of gallons of wastewater into Tampa Bay from Piney Point was intentional to safeguard property and human life near Piney Point, despite the anticipated environmental consequences.  Over 215 millions gallons of wastewater were released, introducing 205 tons of nutrients to lower Tampa over a ten day period, exceeding the amount that is typically introduced in a year.  The TBEP, in collaboration with multiple local, regional, and state entities, coordinated a response-based monitoring effort to document the effects of this release on the bay's resources.  Several dramatic effects were observed over the months following the initial release, the most notable being a massive bloom of the red-tide organism *Karenia brevis* that was likely fueled by the nutrient-rich wastewater. Red tide blooms produce a potent neurotoxin that is fatal for wildlife exposed for sustained periods.  As a result, over 1600 metric tons of dead fish were recovered from Tampa Bay in July 2021.  

This chapter will provide an overview of the history of the Piney Point facility and the effects on the bay during and after the wastewater release, including past incidents prior to 2021.  This information is presented in the context of the long-term recovery of Tampa Bay, the effects on seagrass resources, and how the history of local partnerships were important for the response-based effort.  The reader should have an understanding of how past events, both historically and leading up to 2021, influenced the decision to release wastewater to Tampa Bay and what actions can be taken in the future to prevent similar events from occurring.  The role of TBEP as a facilitator for bay management will be emphasized and the reader should reflect on how the past activities of the program were important for responding to the Piney Point event, in addition to future challenges for managing bay resources in light of the details presented here. 

## Background (1000-2000 words)

The "Bone Valley" in central Florida has supported a multi-billion dollar mining industry for several decades. Its namesake refers to the geological characteristics of the region, also called Karst geology, where fossilized marine organisms have created a limestone base overlying a freshwater aquifer.  This limestone is rich in phosphorus as a main ingredient used in commercially available fertilizer, either for residential use or large-scale agricultural production. Consequently, Tampa Bay waters have relatively large concentrations of phosphorus that aquatic organisms have adapted to over geologic time scales.  Additions of other nutrients, like nitrogen, can substantially alter the balance and pace of biological growth in the estuary.  Because Tampa Bay is "nitrogen-limited", water quality improvements in previous decades have focused on mitigating external sources of nitrogen. However, byproducts from fertilizer production can be rich in both phosphorus and nitrogen.  Fertilizer processing facilities are often located near distribution centers like port facilities and the export of fertilizer is a primary function that the ports of Tampa Bay support. As such, both the production and export of fertilizer present substantial risks for water quality in Tampa Bay.

The production and distribution of fertilizer is a waste intensive process.  For every 1 part useful fertilizer that is produced from raw phosphorus ore, five parts waste are created.  This waste is called phosphogypsum and it has no useful commercial application.  As a result, phosphogypsum is stored on-site as large stacks (or gypstacks) that are visible miles away and are the only topographical features visibible on the flat Florida landscape.  Phosphogypsum is initially produced as a slurry during fertilizer production.  The gypstacks are formed as the solid materials settle out of the slurry, leaving wastewater with similar chemical characteristics as the phosphogypsum. Piney Point historically produced diammonium phosphate ((NH$_4$)$_2$HPO$_4$) and the wastewater stored on site is high in both nitrogen and phosphorus. This wastewater also has no practical use and its disposal through treatment or export elsewhere can be cost-prohibitive.  As a result, phosphogypsum stacks persist long-after production has ceased, with many such examples in the Tampa Bay watershed. Distribution of fertilizer at port facilities can also introduce substantial nutrients to surface waters primarily through losses during physical transport.  Although regulation and adoption of best practices has greatly reduced "material losses" from these activities, nutrient loads from fertilizer transport at ports are still estimated as a non-negligible portion of the overall nutrient budget for Tampa Bay.

The Piney Point facility has a long and complicated history of ownership and management. Fertilizer production began in 1966 when the land was purchased by Borden Chemicals. Early reports described environmental concerns related to surface water contamination in Bishop Harbor immediately adjacent to Piney Point, suspected groundwater contamination from industrial solvents, and air pollution from emissions produced during production.  Mulberry Phosphates, Inc. acquired the facility in 1993 and operated it until 2001 when the company declared bankruptcy, after which regulatory oversight was transferred to FDEP. Mulberry Phosphates was a prominent fertilizer production company in Florida at the time and was also responsible for an unintentional spill of fertilizer process water into the Alafia River in 1997. During its ownership of Piney Point, wastewater was released to Bishop Harber in 2001 due to tropical storm activity and again in November 2003 to October 2004 to ease pressure on the gypstacks. Wastewater was also barged offshore to the Gulf of Mexico during this time as another attempt at maintaining integrity of the facility.  HRK Holdings, LLC purchased Piney Point in August 2006 through an administrative agreement with FDEP.  With oversight by the latter, HRK agreed to maintain Piney Point by agreeing that any future uses must protect and be compatible with integrity of stack closure and long-term care.

Over the course of its ownership, site management decisions by HRK, as approved by FDEP, contributed to a further decline in holding capacity of the gypstacks at Piney Point.  A port expansion project at Port Manatee produced dredge material that HRK agreed to store in the NGS-S holding pond, further reducing holding capacity of the facility.  Wastewater was released in 2011 again to Bishop Harbor as a result of compromised plastic liner in NGS-S, where the addition of dredge material and seawater was suspected as the cause.  HRK Holdings filed for Chapter 11 bankruptcy in 2012 citing expenses associated with the port expansion project and the fallout from the environmental impacts.  Although HRK maintained majority ownership of the site, portions of the property were sold to third parties to alleviate some of the financial burden from the bankruptcy settlement. By 2021, the inability of NGS-S to continue to hold wastewater and dredge material was evident as a leak was identified in NGS-S and later confirmed as being caused by a tear in the plastic liner of the holding pond.  Concerns of public safety and damage to private property motivated the decision to release untreated wastewater from NGS-S directly to Tampa Bay near Port Manatee, as authorized by an emergency order from FDEP. 

From March 30th to April 9th, 2021, over 215 million gallons of wastewater were released from Piney Point into Tampa Bay from a discharge point at Port Manatee. A year's worth of external nutrient inputs entered lower Tampa Bay during this ten day period.  Given the environmental impacts that were expected, the TBEP coordinated a multi-agency response to document the effects on the bay's natural resources.  Public, private, and academic partners collected thousands of water quality samples, measured seagrass and macroalgae coverage, documented changes in sediment quality and the organisms that live on the bay bottom, and assessed algal community changes.  Monitoring efforts were guided by a hydrodynamic flow simulation model developed by academic partners from the College of Marine Science at the University of South Florida.  This model provided an assessment of where the released water was likely to travel, thus providing guidance on where sampling should occur each week.  The TBEP provided support for these effort by having regular meetings with partner agencies to coordinate sampling, serving as a data warehouse for synthesizing monitoring information, creating a public dashboard to communicate changes to the public in near real time, and disseminating monthly one-pagers to communicate results to date. In addition, TBEP staff provided dozens of interviews for local and national media outlets as expert commentary on the event.    

Monitoring of bay resources continued for six months following the initial release.  Throughout this period, several impacts were observed.  First, an immediate and expected response in the algal community near the discharge point was observed as a bloom of commonly-occurring diatoms quickly utilized the nutrients.  The bloom was short-lived and dissipated by the end of April, after which blooms of filamentous cyanobacteria (*Dapis* spp.) were observed near the port and at locations south, often covering seagrasses or floating on the surface.  Increases in macroalgal species were also observed along seagrass monitoring transects. The cyanobacteria blooms decreased in abundance by July, when concentrations of the red-tide organism *Karenia brevis* increased dramatically in the bay. Red tide was first observed outside of Tampa Bay on April 20th, first measured at bloom concentrations in the bay proper on May 23rd, increasing to high bloom concentrations (> 1 million cells / L) by late June, and peaking on July 4th at greater than 10 million cells / L in the middle of Tampa Bay.  Red tide is typically limited in Tampa Bay as freshwater inputs from major rivers lower salinity below the optimal tolerance range.  However, low rainfall during the first half of 2021 contributed to higher than normal salinity that produced favorable conditions for red tide, in addition to increased availability of nutrients from the Piney Point discharge.  As a result, brevetoxins produced by the red tide caused a massive fish kill throughout the bay, where an estimated 1600 metric tons of dead fish were recovered. Numerous reports of marine mammal mortalities were also received during this time.

By September 2021, conditions in the bay were visibly similar to those prior to the release from Piney Point, although monitoring and additional research continued to better understand long-term implications.  A study published two years later demonstrated that wastewater from Piney Point dispersed much further than anticipated, with water having a chemical signature similar to the discharge being observed at a control site over 30 miles to the north of the mouth of Tampa Bay [@morrison2023]. Seagrasses, although not showing aany notable changes in 2021, had declined in total cover on the eastern shore of Tampa Bay based on a comparison of estimates from aerial imagery obtained during the winter of 2020 and 2022.  However, seagrasses consistently declined baywide since 2016 and it is difficult to assess the role of Piney Point in the 2022 decline.  Further work has demonstrated that phosphorous and nitrogen from wastewater discharge from Piney Point, 2021 and previous, can be stored in bay bottom sediments as a potential future source of nutrients [@chappel2025].  These findings highlight the need to better quantify sediment nutrient sources that have likely been influenced by Piney Point discharge, especially when nutrients can be made biologically available in the water column during storm events that resuspend sediments.  Lastly, the fate and effects of lesser studied contaminants from Piney Point have also been a concern. Wastewater from Piney Point has been shown to have elevated microplastic concentrations, presumably from degradation of the plastic liner in the holding ponds.  Microplastics have widespread distribution in Tampa Bay and any attempts to mitigate sources should be made to prevent further negative impacts on bay habitats and wildlife. 

Public response to the events of 2021 was a significant factor influencing future plans for Piney Point.  Motivated by public concerns on the environmental impacts, a lawsuit was filed against HRK holdings by several prominent local conservation groups shortly after the discharge was authorized for release in 2021.  On September 18th, 2024, a US District federal ruled that HRK was in violation of the US Clean Water Act, despite receiving a permit from FDEP to discharge the wastewater in 2021.  This ruling ordered HRK to pay \$56,460 for each day wastewater was released to public waters, totalling \$846,900 for the duration of the event. FDEP concurrently agreed to fund additional future monitoring to assess long-term impacts, with $75,000 paid to the TBEP to organize these efforts. During litigation, public calls for the closure of Piney Point lead to the development and implementation of a closure plan for the facility as adopted and implemented by FDEP.  These plans included using an independent third-party as a court-appointed receiver to oversee the closure process, with specific actions to treat the wastewater onsite prior to pumping the water underground using a deep well injection site.  Wastewater was also sent to local treatment plants to expedite the process.  Once all wastewater is removed, the remaining gypstacks will be filled and capped to reduce future stormwater management needs at the site.  As of writing, only one of the four holding ponds at Piney Point has been succesfully filled.  


Provide background information for the study that relates to the events, design process, etc. Make sure to include sufficient information (including pictures, figures, graphs, etc.) so that a novice (i.e., student) can understand the case study. Include references to the events that allow for the reader to investigate further.

My notes:

What was the response - monitoring effort and environmental (short-term, red tide, present), legal outcomes

What did TBEP do? updates, facilitate monitoring, dashboard, media requests

long-term closure plan for piney point, other facilities in the region - deep well injection, disposal of phosphogypum via road construction?  Piney Point well may be precedent for future activities, but still a lot of unknowns, related to groundwater/drinking water?

Figures:

- map
- water quality
- red tide
- seagrass/macro?
- fisheries (we now have good nekton data to report)

## Student Activities (500-1000 words)

### Classroom discussion questions

Include at least 3 discussion questions based on the case study that can be used in a classroom situation.

My notes:

Something about communication/transparency of information 

Something about history of past partnerships, why were they so important

Something about reactive v proactive, i.e., Piney Point was a disaster waiting to happen, but somethign was only done once it happened.  What are the forces at play that prevent proactive action?

### Individual student responses

Include at least 3 questions/prompts based on the case study that can be used in a homework assignment or on an exam. These could include further reading (be sure to provide references to readily available materials) or personal reflections.

My notes:

Something about interpretation of the figures/tables in this chapter

## Conclusion (500-1000 words)

Include a discussion of key take-aways.

My notes:

Bring everybody to the table (highlight Mosaic's role in the TBNMC)

Something about resiliency and the bay's ability to recover from this event

## References {.unnumbered}
